# Generated by Django 6.0.6 on 2026-07-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('EXTRACTING', 'Extracting ZIP'), ('PARSING', 'Parsing AST'), ('BUILDING_GRAPH', 'Building Knowledge Graph'), ('READY', 'Ready'), ('FAILED', 'Failed')], default='READY', max_length=32),
        ),
    ]
